### ISSUE TITLE
Can you share a IP camera stream without reencoding with that?

### ISSUE THREAD

**Issue by dzek69** [ashellunts/ffmpeg-to-webrtc#2]
As in the title.

I once looked for a solution to push h.264 stream from IP camera without reencoding via WebRTC and failed completely. I don't remember the details, but it got stuck in my head that every solution required re-encoding.

Reencoding multiple 1080p streams would kill the server and I'd like to push several streams via WebRTC at the same time.

Sorry if my question is incomplete at some point - I'm definitely a beginner when it comes to streaming.

**Comment by ashellunts** [comment]
Hi Jacek,

yes it should be possible.

Jacek Nowacki ***@***.***> schrieb am Fr., 24. Sept. 2021,
15:06:

**Comment by ashellunts** [comment]
Do you need any further help?

**Comment by dzek69** [comment]
At this moment no, thank you.

I may need help when i will get onto a project I'm doing again.

Thanks again
