### ISSUE TITLE
"Put SDP from ffmpeg-to-webrtc into your browser"

### ISSUE THREAD

**Issue by ZeoWorks** [ashellunts/ffmpeg-to-webrtc#6]
Hi, where do I find the SDP from ffmpeg-to-webrtc?

I assume it's meant to appear in the commandline?
Nothing seems to appear after such as command is executed;
_go run . -rtbufsize 100M -i test.mp4 -pix_fmt yuv420p -c:v libx264 -bsf:v h264_mp4toannexb -b:v 2M -max_delay 0 -bf 0 -f h264 -_

I added ffmpeg.exe into the src directory.
Thanks!

**Comment by ashellunts** [comment]
Hi, you should add `< SDP.txt` in the end of command line (if on windows) and put in SDP.txt SDP from browser.
