### ISSUE TITLE
How to stream rtsp streams with copy codec to webrtc.

### ISSUE THREAD

**Issue by anand-010** [ashellunts/ffmpeg-to-webrtc#7]
I am trying to stream my cctv streams to webrtc i have alredy tested many commands none of them works.
It returns "All video frames parsed and sent"
Please help me.
I am using windows planning to deploy on linux.

**Comment by anand-010** [comment]
So far this is the only command worked for men
`go run . -rtbufsize 100M -f gdigrab -framerate 30 -i desktop -pix_fmt yuv420p -c:v libx264 -b:v 2M -max_delay 0 -bf 0 -f h264 - < SDP.txt`
none of examples also worked.

**Comment by ashellunts** [comment]
If you have "All video frames parsed and sent", there should be some error in ffmpeg. Try running ffmpeg directly with the same options and check that it works. After that use same commands in the app.
